
export type Package = {
  id: string;
  slug: string;
  name: string;
  image: string;
  description: string;
  price: number;
  duration: string;
  transport: ('Train' | 'Flight' | 'Heli' | 'Bus')[];
  featured: boolean;
  itinerary: { day: number | string; title: string; description: string }[];
  inclusions: string[];
  exclusions: string[];
};

export const packages: Package[] = [
  {
    id: 'char-dham-yatra-by-bus',
    slug: 'char-dham-yatra-by-bus',
    name: 'Char Dham Yatra by Bus',
    image: 'https://firebasestorage.googleapis.com/v0/b/nityholiday-adventures.firebasestorage.app/o/Char%20Dham%20Yatra%20by%20Bus.png?alt=media&token=0d1ba896-d8bf-4d89-9ae2-602e767ad757',
    description: 'Experience the divine Char Dham pilgrimage in comfort on an air-conditioned bus.',
    price: 42000,
    duration: '10 Days/9 Nights',
    transport: ['Bus'],
    featured: true,
    itinerary: [
      {
        day: 1,
        title: 'Haridwar → Barkot',
        description: 'Depart Haridwar after the Ganga Aarti. Scenic drive via Rishikesh, Devprayag, Mussoorie. Optional stop at Kempty Falls. Overnight in Barkot.',
      },
      {
        day: 2,
        title: 'Yamunotri Darshan',
        description: 'Drive to Janki Chatti & 6 km trek to Yamunotri Temple. Temple darshan & holy dip in Surya Kund. Visit the Divya Shila rock. Return & overnight in Barkot.',
      },
      {
        day: 3,
        title: 'Barkot → Uttarkashi',
        description: 'Visit Prakateshwar Mahadev Temple, Kashi Vishwanath Temple & Shakti Temple. Overnight in Uttarkashi.',
      },
      {
        day: 4,
        title: 'Gangotri Darshan',
        description: 'Drive through Harsil Valley to Gangotri. Holy dip in the Bhagirathi River & Ganga Aarti. Return & overnight in Uttarkashi.',
      },
      {
        day: 5,
        title: 'Uttarkashi → Phata',
        description: 'En-route views of Tehri Dam. Stop at Rudraprayag Sangam & Ardh Narishwar Temple. Overnight in Phata.',
      },
      {
        day: 6,
        title: 'Kedarnath Darshan (Day 1)',
        description: 'Trek from Phata to Kedarnath (approx. 16 km). Participate in evening Aarti & visit Bhairavnath Temple. Overnight in Kedarnath.',
      },
      {
        day: 7,
        title: 'Kedarnath Darshan (Day 2)',
        description: 'Morning darshan at Bholenath temple and return trek to Phata.',
      },
      {
        day: 8,
        title: 'Phata → Pandukeshwar',
        description: 'Drive via Ukhimath & Chopta (“Mini Switzerland”). Photo-stop at Vishnuprayag confluence. Overnight in Pandukeshwar.',
      },
      {
        day: 9,
        title: 'Badrinath & Mana Village',
        description: 'Darshan at Badrinath Temple & holy dip in Tapti Kund. Explore Mana Village, Vyas Gufa & Ganesh Gufa. Return & overnight in Pandukeshwar.',
      },
      {
        day: 10,
        title: 'Pandukeshwar → Haridwar',
        description: 'Drive back via Joshimath & Rudraprayag. Optional halt in Rishikesh. Tour concludes on arrival in Haridwar.',
      },
    ],
    inclusions: [
      '9 nights’ comfortable hotel accommodation',
      'Daily breakfast',
      'Air-conditioned bus transport throughout',
      'Experienced local guide',
      'All temple entry and parking fees',
      'Basic travel insurance',
    ],
    exclusions: [
      'Pony/Palki/Helicopter charges',
      'VIP Darshan tickets',
      'Lunches and dinners',
      'Any personal expenses',
    ],
  },
  {
    id: 'char-dham-yatra-by-helicopter',
    slug: 'char-dham-yatra-by-helicopter',
    name: 'Char Dham Yatra by Helicopter',
    image: 'https://firebasestorage.googleapis.com/v0/b/nityholiday-adventures.firebasestorage.app/o/Char%20Dham%20Yatra%20by%20Helicopter.png?alt=media&token=d71a5386-65bb-4a91-a57e-197394814d33',
    description: 'Experience the sacred Char Dham in ultimate comfort and time-efficiency aboard our VIP helicopter service.',
    price: 276000,
    duration: '6 Days/5 Nights',
    transport: ['Heli', 'Bus'],
    featured: true,
    itinerary: [
      {
        day: 1,
        title: 'Haridwar → Barkot (by road)',
        description: 'VIP departure from Haridwar early morning. Luxury coach transfer via Mussoorie to Barkot. Check-in at premium mountain resort. Evening at leisure to acclimatize.',
      },
      {
        day: 2,
        title: 'Yamunotri (by helicopter)',
        description: 'Helicopter flight from Barkot helipad to Yamunotri. Temple darshan & rituals. Holy dip in Surya Kund. Scenic helicopter return to Barkot. Overnight stay in Barkot.',
      },
      {
        day: 3,
        title: 'Gangotri (by helicopter)',
        description: 'Direct helicopter transfer to Gangotri. Bhagirathi River Aarti & temple prayers. Explore nearby Bhairav Temple. Return flight to Uttarkashi helipad. Overnight in Uttarkashi.',
      },
      {
        day: 4,
        title: 'Kedarnath (by helicopter)',
        description: 'Early-morning helicopter from Uttarkashi to Kedarnath. Temple darshan, Bhairavnath Temple visit. Enjoy mountain vistas from helipad. Overnight at deluxe forest lodge near Kedarnath.',
      },
      {
        day: 5,
        title: 'Badrinath (by helicopter)',
        description: 'Helicopter flight to Badrinath. Darshan & rituals at Badrinath Temple. Visit Mana Village, Ganesh Gufa & Vyas Gufa. Return to Dehradun by coach or helicopter (weather dependent). Overnight in Dehradun.',
      },
      {
        day: 6,
        title: 'Departure to Haridwar',
        description: 'Final helicopter or luxury coach transfer back to Haridwar. Tour concludes with blessings and fond memories.',
      },
    ],
    inclusions: [
      '5 nights’ luxury accommodation (4★–5★)',
      'All helicopter transfers as per itinerary',
      'Luxury coach transfers where required',
      'Daily buffet breakfast & dinner',
      'Expert spiritual guide & local escorts',
      'VIP temple access (bypass queues)',
      'Comprehensive travel insurance',
      '24/7 emergency support',
    ],
    exclusions: ['Personal expenses', 'Additional sightseeing', 'Tips and gratuities'],
  },
  {
    id: 'living-desert-camp',
    slug: 'living-desert-camp',
    name: '2 Days / 2 Nights Living Desert Camp',
    image: 'https://picsum.photos/seed/living-desert/600/400',
    description: 'Discover the charm of Rajasthan with our exclusive 2 Days / 2 Nights Living Desert Camp package. Enjoy a royal stay in luxury Swiss tents, mesmerizing camel and jeep safaris, Rajasthani folk music, traditional cuisine, and unforgettable sunsets amidst the golden dunes. Perfect for travelers who want to feel the true desert spirit with comfort and culture.',
    price: 5500,
    duration: '2 Days / 2 Nights',
    transport: ['Bus'],
    featured: true,
    itinerary: [
      {
        day: 1,
        title: 'Arrival and Desert Activities',
        description: 'Arrive at the camp and receive a traditional welcome with a refreshing drink. In the evening, enjoy a camel safari to the sunset point, followed by snacks, tea, and coffee. The night comes alive with Rajasthani folk music, dance, and a DJ group dance session before a delicious Rajasthani dinner.',
      },
      {
        day: 2,
        title: 'Safari and Departure',
        description: 'After a hearty morning breakfast, embark on an adventurous jeep safari across the dunes. After the safari, the tour concludes, and you depart from the camp with unforgettable memories.',
      },
    ],
    inclusions: [
      'Camel Safari',
      'Jeep Safari',
      'Traditional Welcome Ceremony & Welcome Drink',
      'Evening Tea, Coffee, and Snacks',
      'Rajasthani Folk Music & Dance',
      'DJ Group Dance Night',
      'Authentic Rajasthani Dinner',
      'Overnight Stay in Luxury Swiss Tent',
      'Morning Breakfast',
      'Power Backup',
      'Hot Water Facility',
    ],
    exclusions: [
      'Transport to and from the camp',
      'Lunch',
      'Any personal expenses',
      'Alcoholic beverages',
    ],
  },
  {
    id: 'auli-mussoorie-dehradun-adventure-package',
    slug: 'auli-mussoorie-dehradun-adventure-package',
    name: 'Auli Mussoorie Dehradun Adventure',
    image: 'https://firebasestorage.googleapis.com/v0/b/nityholiday-adventures.firebasestorage.app/o/Auli%20Mussoorie%20Dehradun%20Adventure.png?alt=media&token=629fb55a-5a64-450b-bfef-769b335d70b3',
    description: 'Discover the scenic beauty of Uttarakhand on this action-packed 5 Days/4 Nights adventure trip.',
    price: 45000,
    duration: '5 Days/4 Nights',
    transport: ['Bus'],
    featured: true,
    itinerary: [
      { day: 1, title: 'Dehradun → Mussoorie', description: 'Pickup from Dehradun airport/railway station. 1.5 hour scenic drive to Mussoorie. Evening leisure & shopping on Mall Road. Overnight stay in Mussoorie.' },
      { day: 2, title: 'Mussoorie Sightseeing', description: 'Visit Kempty Falls & enjoy natural cascades. Ride to Gun Hill for panoramic views. Explore Company Garden’s manicured lawns. Boating on Mussoorie Lake. Wander local markets for souvenirs. Overnight in Mussoorie.' },
      { day: 3, title: 'Mussoorie → Auli', description: 'Scenic drive through Himalayan foothills. Photo-stops at mountain viewpoints. Check-in at your Auli resort. Evening at leisure to soak in alpine air. Overnight in Auli.' },
      { day: 4, title: 'Auli Adventures', description: 'Ride Asia’s longest cable car (Gondola). Optional skiing session (seasonal). Guided trek on Gorson Bugyal meadows. Visit Auli’s crystal-clear artificial lake. Overnight in Auli.' },
      { day: 5, title: 'Auli → Dehradun', description: 'Morning breakfast with mountain vistas. Drive back to Dehradun via charming villages. Drop-off at Dehradun station or airport. Tour concludes.' },
    ],
    inclusions: [
      '4 nights’ comfortable hotel/resort accommodation',
      'Daily breakfast & dinner',
      'All transfers by private vehicle',
      'Experienced local guide',
      'Sightseeing entrance fees & cable car fare',
      'Basic travel insurance'
    ],
    exclusions: [ 'Airfare/train fare', 'Lunches', 'Skiing charges', 'Personal expenses' ],
  },
  {
    id: 'spiritual-uttarakhand-tour',
    slug: 'spiritual-uttarakhand-tour',
    name: 'Spiritual Uttarakhand Tour',
    image: 'https://firebasestorage.googleapis.com/v0/b/nityholiday-adventures.firebasestorage.app/o/Uttarakhand%20Holy%20%26%20Adventure%20Tour.png?alt=media&token=adc826b4-6f6e-47be-9e66-e1e326eb11dd',
    description: 'Embark on a soul-nourishing journey through Uttarakhand’s most sacred spots.',
    price: 35000,
    duration: '4 Days/3 Nights',
    transport: ['Bus'],
    featured: true,
    itinerary: [
      { day: 1, title: 'Dehradun Arrival & Temple Visits', description: 'Airport/railway pickup in Dehradun. Visit the ancient Tapkeshwar Temple and attend evening Aarti. Check-in and overnight stay in Dehradun.' },
      { day: 2, title: 'Mussoorie Exploration', description: 'Scenic drive to Mussoorie. Darshan at Jwala Devi Temple. Cable-car ride to Gun Hill for panoramic views. Stroll and shopping on Mall Road. Overnight stay in Mussoorie.' },
      { day: 3, title: 'Rishikesh Spiritual Experience', description: 'Transfer to Rishikesh in the morning. Visit Triveni Ghat and participate in Ganga Aarti at sunset. Optional white-water rafting (gentle grade) or riverside yoga session. Overnight stay in Rishikesh.' },
      { day: 4, title: 'Departure via Dehradun', description: 'Early-morning temple visit (choose from Lakshman Jhula or Neelkanth Mahadev). Return drive to Dehradun. Drop-off at airport/railway station; tour concludes.' },
    ],
    inclusions: [
      '3 nights’ accommodation in well-appointed hotels',
      'Daily buffet breakfast',
      'All transfers by private, air-conditioned vehicle',
      'Expert spiritual guide throughout the journey',
      'Entry and puja offerings at all listed temples',
      'Gentle rafting or guided yoga session in Rishikesh',
      'Basic travel insurance',
    ],
    exclusions: [ 'Airfare/train fare', 'Lunches and dinners', 'Optional activity costs', 'Personal expenses' ],
  },
  {
    id: 'splendid-andaman',
    slug: 'splendid-andaman',
    name: 'Splendid Andaman (2N Port Blair + 2N Havelock + 1N Neil)',
    image: 'https://picsum.photos/seed/splendid-andaman/600/400',
    description: 'Embark on an unforgettable journey to the Andaman Islands. This package covers Port Blair, Havelock, and Neil Island, offering a perfect blend of adventure and relaxation.',
    price: 81500,
    duration: '6 Days/5 Nights',
    transport: ['Flight'],
    featured: false,
    itinerary: [
        { day: 1, title: 'Airport Pickup, Carbyns Cove Beach, Cellular Jail & Light and Sound Show', description: 'Arrive at Port Blair Airport and transfer to your hotel. Later, proceed to Corbyns Cove Beach. In the evening, attend the enthralling Sound and Light Show at Cellular Jail, which brings the heroic saga of the Indian freedom struggle to life.' },
        { day: 2, title: 'Port Blair to Havelock, Radhanagar Beach', description: 'Depart from Port Blair to Havelock Island on a ferry. Upon arrival, check into your hotel. Later, visit one of Asia\'s best beaches, Radhanagar Beach, and enjoy the beautiful sunset.' },
        { day: 3, title: 'Elephant Beach Tour & Snorkelling', description: 'Take a boat to Elephant Beach, one of the most visited snorkeling destinations. Enjoy a complimentary snorkeling session and explore the vibrant coral reefs. Return to your hotel in the afternoon.' },
        { day: 4, title: 'Havelock to Neil Island, Laxmanpur Beach Sunset', description: 'Board a premium cruise to Neil Island. Check into your resort and later visit Laxmanpur Beach to witness a magnificent sunset.' },
        { day: 5, title: 'Bharatpur Beach, Natural Rock Formation, Return to Port Blair', description: 'After breakfast, visit the Natural Rock Formation and Bharatpur Beach, where you can indulge in water sports. Later, board a cruise back to Port Blair for an overnight stay.' },
        { day: 6, title: 'Drop to the Airport', description: 'Check out from the hotel and proceed to the airport for your return journey with sweet memories of this exotic destination.' },
    ],
    inclusions: [
      'Accommodation with Breakfast and Dinner at all Hotels.',
      'All transfers by private AC Ertiga car at Port Blair, Havelock Island, & Neil Island.',
      'Entry & Ferry tickets to all mentioned places.',
      'Elephanta Island speed boat charges.',
      'Inter-Island transfers by AC Luxury tourist ferry (Govt. ferry if private is unavailable).',
      'Airport and Jetty pickup/drop.',
      'All taxes.',
    ],
    exclusions: [
      'Lunch',
      'Any kind of ship fare.',
      'Extra excursions not in the itinerary.',
      'Water sports activities.',
      'Personal expenses (laundry, room services, etc.).',
      'Expenses due to unforeseen circumstances like bad weather or political unrest.',
    ],
  },
  {
    id: 'gujarat-heritage-wildlife-tour',
    slug: 'gujarat-heritage-wildlife-tour',
    name: 'Gujarat Heritage & Wildlife Tour',
    image: 'https://firebasestorage.googleapis.com/v0/b/nityholiday-adventures.firebasestorage.app/o/Gujarat%20Heritage%20%26%20Wildlife%20Tour.png?alt=media&token=44ba35c9-1bf5-4b90-aaef-439d62296114',
    description: 'Discover Gujarat’s vibrant heritage and untamed wildlife on this immersive 7-day journey.',
    price: 25000,
    duration: '7 Days/6 Nights',
    transport: ['Bus'],
    featured: false,
    itinerary: [
      { day: 1, title: 'Ahmedabad Heritage', description: 'Heritage walking tour in the old city. Visit Sabarmati Ashram, the home of Mahatma Gandhi.' },
      { day: 2, title: 'Ahmedabad Exploration', description: 'Marvel at the intricate Adalaj Stepwell. Evening stroll & local snacks at Manek Chowk night market.' },
      { day: 3, title: 'Gir National Park Safari', description: 'Early-morning jungle safari in search of the Asiatic lion. Expert naturalist–led wildlife spotting (deer, birds, reptiles).' },
      { day: 4, title: 'Gir Culture', description: 'Visit a nearby tribal village for cultural exchange. Evening folk dance performance under the stars.' },
      { day: 5, title: 'Somnath Temple', description: 'Darshan at the majestic Somnath Temple. Leisure time on Somnath’s pristine beach. Attend the moving Ganga Aarti at sunset.' },
      { day: 6, title: 'Dwarka & Bet Dwarka', description: 'Morning darshan at Dwarkadhish Temple. Boat ride to Bet Dwarka island & Krishna’s Dwarka archaeology site.' },
      { day: 7, title: 'Nageshwar & Departure', description: 'Visit Nageshwar Jyotirlinga Temple. Return journey to Ahmedabad/departure point.' },
    ],
    inclusions: [
      '6 nights’ comfortable hotel stays (3★–4★)',
      'Daily buffet breakfast',
      'Air-conditioned vehicle with driver for entire tour',
      '2 safari rides in Gir National Park (shared jeep)',
      'Expert naturalist & local guides',
      'All monument, safari & boat fees',
      'Basic travel insurance'
    ],
    exclusions: [ 'Lunches and dinners', 'Airfare/train fare', 'Personal expenses' ],
  },
  {
    id: 'royal-rajasthan-explorer',
    slug: 'royal-rajasthan-explorer',
    name: 'Royal Rajasthan Explorer',
    image: 'https://firebasestorage.googleapis.com/v0/b/nityholiday-adventures.firebasestorage.app/o/Royal%20Rajasthan%20Explorer.png?alt=media&token=b87488cc-ebb4-4688-a963-2c43e2cc59cd',
    description: 'Embark on a regal journey through the “Land of Kings.” This 8-day adventure immerses you in Rajasthan’s royal heritage.',
    price: 55000,
    duration: '8 Days / 7 Nights',
    transport: ['Bus', 'Flight'],
    featured: false,
    itinerary: [
      { day: 1, title: 'Arrival in Jaipur', description: 'Pickup from Jaipur airport/railway station. Check-in at your heritage hotel. Evening visit to Birla Temple and local bazaar stroll. Overnight stay in Jaipur.' },
      { day: 2, title: 'Jaipur Sightseeing', description: 'Early-morning Amber Fort (elephant ride option). City Palace & Jantar Mantar. Hawa Mahal (Palace of Winds) photo stop. Explore Johri Bazaar. Overnight in Jaipur.' },
      { day: 3, title: 'Jaipur → Jodhpur', description: 'Scenic drive to Jodhpur (approx. 6 hours). En-route photo stop at Pushkar Lake & Brahma Temple. Check-in at a heritage haveli in Jodhpur. Sunset views from Rao Jodha Desert Rock Park. Overnight in Jodhpur.' },
      { day: 4, title: 'Jodhpur Sightseeing', description: 'Mehrangarh Fort guided tour. Jaswant Thada cenotaph visit. Clock Tower & Sardar Market exploration. Overnight in Jodhpur.' },
      { day: 5, title: 'Jodhpur → Jaisalmer', description: 'Drive through the Thar desert to Jaisalmer (approx. 5 hours). Check-in at your desert-themed hotel. Late-afternoon camel safari & sunset at Sam Sand Dunes. Overnight in a desert camp.' },
      { day: 6, title: 'Jaisalmer Sightseeing', description: 'Jaisalmer Fort (Sonar Quila) walking tour. Patwon Ki Haveli & Salim Singh Ki Haveli. Gadisar Lake boat ride & nearby temples. Overnight in Jaisalmer.' },
      { day: 7, title: 'Jaisalmer → Udaipur', description: 'Morning flight or long-drive transfer to Udaipur. Check-in at a lakeside hotel. Sunset boat ride on Lake Pichola. Overnight in Udaipur.' },
      { day: 8, title: 'Udaipur Sightseeing & Departure', description: 'City Palace & Crystal Gallery tour. Saheliyon Ki Bari (Garden of the Maidens). Jagdish Temple visit & Monsoon Palace viewpoint. Drop-off at Udaipur airport/railway station; tour concludes.' },
    ],
    inclusions: [
      '7 nights’ heritage & premium hotel accommodation',
      'Daily buffet breakfast',
      'All transfers by private, air-conditioned vehicle',
      'Experienced local guide on sightseeing days',
      'Elephant ride at Amber Fort (if operational)',
      'Camel safari & desert camp overnight (with cultural show)',
      'Boat rides at Gadisar & Pichola lakes',
      'All monument entry fees & parking charges',
      'Basic travel insurance',
    ],
    exclusions: ['Airfare/train fare', 'Lunches', 'Personal expenses'],
  }
];
